/**
 * TARAS 2K26 — Supabase Storage & Payment Proof Service
 *
 * Dedicated service for:
 * - Controlled path generation: registrations/{registrationId}/payment-proof.webp
 * - In-browser upload of pre-optimized payment proofs to private Supabase Storage
 * - Atomic persistence of payment metadata and references in Cloud Firestore
 * - Secure temporary signed URL retrieval for Registration Staff & Admin review
 * - Safe replacement & cleanup logic without affecting verified proofs
 *
 * CRITICAL ARCHITECTURAL CONSTRAINTS:
 * - Uses only the public/anon Supabase client.
 * - Firebase Authentication remains the sole user identity provider.
 * - Binary image data is NEVER stored in Firestore.
 */

import {
  collection,
  doc,
  getDocs,
  setDoc,
  updateDoc,
  query,
  where,
  serverTimestamp,
} from 'firebase/firestore';
import { firestore } from '../config/firebase';
import { getSupabaseClient, isSupabaseConfigured } from '../config/supabase';

export const SUPABASE_PAYMENT_PROOF_BUCKET = 'payment-proofs';

export interface SupabasePaymentProofMetadata {
  provider: 'supabase';
  bucket: string;
  path: string;
  fileSize: number;
  contentType: string;
  uploadedAt: string;
  signedUrl?: string;
}

export interface SupabaseUploadProgressCallback {
  (percentage: number): void;
}

/**
 * Generate controlled and sanitized storage path for registration payment proof.
 * Format: registrations/{registrationId}/payment-proof.{ext}
 */
export function getPaymentProofStoragePath(
  registrationId: string,
  fileExtension = 'webp'
): string {
  const cleanRegId = registrationId.trim().replace(/[^a-zA-Z0-9_-]/g, '');
  const cleanExt = fileExtension.toLowerCase().replace(/[^a-z0-9]/g, '');
  return `registrations/${cleanRegId}/payment-proof.${cleanExt || 'webp'}`;
}

/**
 * Upload pre-optimized payment screenshot directly to Supabase Storage.
 */
export async function uploadPaymentProofToSupabase(
  registrationId: string,
  file: File | Blob,
  onProgress?: SupabaseUploadProgressCallback
): Promise<SupabasePaymentProofMetadata> {
  if (!isSupabaseConfigured) {
    throw new Error(
      'Supabase Storage is not yet configured. Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local.'
    );
  }

  if (!registrationId) {
    throw new Error('Registration ID is required for storage path resolution.');
  }

  if (!file || file.size === 0) {
    throw new Error('No valid payment screenshot file provided.');
  }

  const supabase = getSupabaseClient();
  const rawExt = file instanceof File ? file.name.split('.').pop() || 'webp' : 'webp';
  const cleanExt = rawExt.toLowerCase().includes('png')
    ? 'png'
    : rawExt.toLowerCase().includes('jpg') || rawExt.toLowerCase().includes('jpeg')
      ? 'jpeg'
      : 'webp';

  const storagePath = getPaymentProofStoragePath(registrationId, cleanExt);
  const contentType = file.type || (cleanExt === 'webp' ? 'image/webp' : 'image/jpeg');

  if (onProgress) onProgress(15);

  // Set up progress indicator
  const progressTimer = setInterval(() => {
    if (onProgress) {
      onProgress(Math.floor(25 + Math.random() * 65));
    }
  }, 250);

  try {
    const { data, error } = await supabase.storage
      .from(SUPABASE_PAYMENT_PROOF_BUCKET)
      .upload(storagePath, file, {
        contentType,
        upsert: true, // Allow replacing for resubmissions
        cacheControl: '3600',
      });

    clearInterval(progressTimer);

    if (error) {
      console.error('Supabase Storage upload error:', error);
      throw new Error(
        `Failed to upload screenshot to Supabase Storage: ${error.message}`
      );
    }

    if (onProgress) onProgress(100);

    const uploadedAt = new Date().toISOString();

    return {
      provider: 'supabase',
      bucket: SUPABASE_PAYMENT_PROOF_BUCKET,
      path: data?.path || storagePath,
      fileSize: file.size,
      contentType,
      uploadedAt,
    };
  } catch (err: any) {
    clearInterval(progressTimer);
    throw new Error(
      err.message ||
        'Payment proof upload failed due to a network interruption. Please retry.'
    );
  }
}

/**
 * Generate a short-lived temporary signed URL to view a private payment proof.
 * Used by Registration Team & Admin verification dashboards.
 */
export async function getPaymentProofSignedViewUrl(
  storagePath: string,
  expiresInSeconds = 300 // 5 minutes default
): Promise<string> {
  if (!isSupabaseConfigured) {
    throw new Error('Supabase Storage is not configured.');
  }

  const supabase = getSupabaseClient();
  const { data, error } = await supabase.storage
    .from(SUPABASE_PAYMENT_PROOF_BUCKET)
    .createSignedUrl(storagePath, expiresInSeconds);

  if (error) {
    console.error('Error creating Supabase signed view URL:', error);
    throw new Error(`Unable to load payment proof: ${error.message}`);
  }

  if (!data?.signedUrl) {
    throw new Error('Signed URL was not generated by Supabase Storage.');
  }

  return data.signedUrl;
}

export interface SavePaymentSubmissionParams {
  registrationId: string;
  utrNumber: string;
  proofMetadata: SupabasePaymentProofMetadata;
}

/**
 * Atomically persist payment submission in Firestore.
 *
 * Sequence:
 * 1. Validates UTR format
 * 2. Checks for duplicate UTR usage across other registrations
 * 3. Updates Firestore registration with paymentProof metadata
 * 4. Sets status = 'PAYMENT_VERIFICATION_PENDING'
 * 5. Logs audit entry in 'audit_logs'
 */
export async function savePaymentProofSubmissionToFirestore({
  registrationId,
  utrNumber,
  proofMetadata,
}: SavePaymentSubmissionParams): Promise<void> {
  const trimmedUtr = utrNumber.trim();
  if (!trimmedUtr) throw new Error('UTR / Transaction ID is required.');
  if (!proofMetadata?.path) {
    throw new Error('Payment screenshot storage path is missing.');
  }

  // Duplicate UTR check across other registrations
  const regsRef = collection(firestore, 'registrations');
  const duplicateQuery = query(regsRef, where('utrNumber', '==', trimmedUtr));
  const duplicateSnap = await getDocs(duplicateQuery);

  let possibleDuplicate = false;
  for (const documentSnap of duplicateSnap.docs) {
    if (documentSnap.id !== registrationId) {
      possibleDuplicate = true;
      break;
    }
  }

  const regRef = doc(firestore, 'registrations', registrationId);
  const now = new Date().toISOString();

  // Atomically persist storage references and set status to PAYMENT_VERIFICATION_PENDING
  await updateDoc(regRef, {
    utrNumber: trimmedUtr,
    paymentProof: {
      provider: 'supabase',
      bucket: proofMetadata.bucket,
      path: proofMetadata.path,
      fileSize: proofMetadata.fileSize,
      contentType: proofMetadata.contentType,
      uploadedAt: proofMetadata.uploadedAt,
    },
    // Maintain backwards-compatible fields for existing queries
    paymentScreenshotPath: proofMetadata.path,
    paymentScreenshotSize: proofMetadata.fileSize,
    paymentScreenshotContentType: proofMetadata.contentType,
    paymentSubmittedAt: now,
    status: 'PAYMENT_VERIFICATION_PENDING',
    possibleDuplicate,
    updatedAt: serverTimestamp(),
  });

  // Audit log entry
  try {
    const auditRef = doc(collection(firestore, 'audit_logs'));
    await setDoc(auditRef, {
      action: 'PAYMENT_SUBMITTED',
      registrationId,
      utrNumber: trimmedUtr,
      provider: 'supabase',
      storagePath: proofMetadata.path,
      fileSize: proofMetadata.fileSize,
      possibleDuplicate,
      timestamp: serverTimestamp(),
    });
  } catch (auditErr) {
    console.warn('Audit log write error:', auditErr);
  }
}

/**
 * Resubmit payment proof following administrative rejection.
 */
export async function resubmitPaymentProofToFirestore({
  registrationId,
  utrNumber,
  proofMetadata,
}: SavePaymentSubmissionParams): Promise<void> {
  const trimmedUtr = utrNumber.trim();
  if (!trimmedUtr) throw new Error('UTR / Transaction ID is required.');

  const regsRef = collection(firestore, 'registrations');
  const duplicateQuery = query(regsRef, where('utrNumber', '==', trimmedUtr));
  const duplicateSnap = await getDocs(duplicateQuery);

  let possibleDuplicate = false;
  for (const documentSnap of duplicateSnap.docs) {
    if (documentSnap.id !== registrationId) {
      possibleDuplicate = true;
      break;
    }
  }

  const regRef = doc(firestore, 'registrations', registrationId);
  const now = new Date().toISOString();

  await updateDoc(regRef, {
    utrNumber: trimmedUtr,
    paymentProof: {
      provider: 'supabase',
      bucket: proofMetadata.bucket,
      path: proofMetadata.path,
      fileSize: proofMetadata.fileSize,
      contentType: proofMetadata.contentType,
      uploadedAt: proofMetadata.uploadedAt,
    },
    paymentScreenshotPath: proofMetadata.path,
    paymentScreenshotSize: proofMetadata.fileSize,
    paymentScreenshotContentType: proofMetadata.contentType,
    paymentSubmittedAt: now,
    status: 'PAYMENT_VERIFICATION_PENDING',
    possibleDuplicate,
    updatedAt: serverTimestamp(),
  });

  try {
    const auditRef = doc(collection(firestore, 'audit_logs'));
    await setDoc(auditRef, {
      action: 'PAYMENT_RESUBMITTED',
      registrationId,
      utrNumber: trimmedUtr,
      provider: 'supabase',
      storagePath: proofMetadata.path,
      fileSize: proofMetadata.fileSize,
      possibleDuplicate,
      timestamp: serverTimestamp(),
    });
  } catch (auditErr) {
    console.warn('Audit log write error:', auditErr);
  }
}
