import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Lock, Eye, Bug, ArrowLeft, Database, Key } from 'lucide-react';
import { Button } from '../../components/common/Button';

export const SecurityPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10 text-slate-300">
      {/* Header */}
      <div className="space-y-4 border-b border-[#dc2626]/30 pb-6">
        <Link to="/" className="inline-flex items-center gap-2 text-xs font-mono text-slate-400 hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4 text-[#dc2626]" /> Back to Homepage
        </Link>
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-2xl bg-[#1a0000] border border-[#dc2626]/60 text-[#dc2626]">
            <ShieldCheck className="w-8 h-8" />
          </div>
          <div>
            <span className="text-[10px] font-mono font-bold text-[#dc2626] uppercase tracking-widest block">
              LEGAL & COMPLIANCE
            </span>
            <h1 className="text-3xl sm:text-4xl font-black text-white font-mono uppercase tracking-tight">
              SECURITY & DATA PROTECTION
            </h1>
          </div>
        </div>
        <p className="text-xs font-mono text-slate-400">
          Security Architecture, Certificate Cryptography & Responsible Disclosure
        </p>
      </div>

      {/* Overview */}
      <div className="p-6 rounded-2xl bg-[#0a0c10] border border-[#dc2626]/40 space-y-3">
        <h2 className="text-lg font-bold text-white font-mono flex items-center gap-2">
          <Lock className="w-5 h-5 text-[#dc2626]" /> Technical Security Controls
        </h2>
        <p className="text-xs sm:text-sm text-slate-300 font-mono leading-relaxed">
          The TARAS 2K26 platform is engineered using modern cloud security practices to protect student data, verify digital payments, and guarantee certificate authenticity.
        </p>
      </div>

      {/* Sections */}
      <div className="space-y-8 text-xs sm:text-sm font-mono leading-relaxed">
        <section className="space-y-3">
          <h3 className="text-base font-bold text-white border-l-2 border-[#dc2626] pl-3 uppercase">
            1. Role-Based Identity & Authorization
          </h3>
          <p className="text-slate-300">
            System privileges are dynamically governed by multi-tier Firestore security rules:
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-slate-400 pl-2">
            <li><strong className="text-white">Participants:</strong> Can only read and write their own profile and team rosters. Client-side attempts to elevate roles to admin or staff are strictly denied by database rules.</li>
            <li><strong className="text-white">Staff & Registration Team:</strong> Granted access exclusively to gate check-in scanning and payment verification queues.</li>
            <li><strong className="text-white">Coordinators:</strong> Authorized to mark attendance and record competition scores for assigned event tracks only.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-bold text-white border-l-2 border-[#dc2626] pl-3 uppercase">
            2. Payment Proof Isolation
          </h3>
          <p className="text-slate-300">
            Payment screenshots uploaded by participants are stored in private Supabase Storage buckets with strict signed-URL duration limits. Payment images are never exposed to public search engines or unauthorized participants.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-bold text-white border-l-2 border-[#dc2626] pl-3 uppercase">
            3. Cryptographic Certificate Verification
          </h3>
          <p className="text-slate-300">
            Every e-certificate generated by TARAS 2K26 contains a unique SHA-256 hash reference stored immutably in Firestore. Scanning the QR code on any certificate links directly to <strong className="text-[#dc2626]">/verify/:certificateId</strong> to confirm authenticity.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-bold text-white border-l-2 border-[#dc2626] pl-3 uppercase">
            4. Responsible Disclosure & Security Contact
          </h3>
          <p className="text-slate-300">
            If you discover a security vulnerability or potential privacy defect on the TARAS 2K26 platform, please report it responsibly to the technical team:
          </p>
          <div className="p-4 rounded-xl bg-[#0a0c10] border border-slate-800 flex items-center gap-3">
            <Bug className="w-5 h-5 text-[#dc2626]" />
            <div>
              <div className="text-white font-bold">TARAS Security Response Desk</div>
              <a href="mailto:taras2k26@gmail.com" className="text-[#dc2626] hover:underline text-xs">
                taras2k26@gmail.com
              </a>
            </div>
          </div>
        </section>
      </div>

      {/* Footer Navigation */}
      <div className="pt-6 border-t border-slate-800 flex items-center justify-between">
        <Link to="/privacy">
          <Button variant="outline" size="sm">
            View Privacy Policy →
          </Button>
        </Link>
        <Link to="/">
          <Button variant="glow" size="sm">
            Return Home
          </Button>
        </Link>
      </div>
    </div>
  );
};
