import React, { useState, useEffect } from 'react';
import type { ParticipantProfile } from '../../types/participant';
import {
  generateParticipantExport,
  subscribeLatestExportMetadata,
  type ExportMetadata,
} from '../../services/participantExportService';
import {
  Download,
  FileSpreadsheet,
  FileText,
  ShieldCheck,
  Sparkles,
  Clock,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
} from 'lucide-react';
import { Button } from '../common/Button';
import { Badge } from '../common/Badge';

interface Props {
  profile: ParticipantProfile | null;
  title?: string;
  subtitle?: string;
}

export const ParticipantDataExportConsole: React.FC<Props> = ({
  profile,
  title = 'Participant Data Export Console',
  subtitle = 'Generate secure, comprehensive operational participant & team reports directly from canonical Firestore data.',
}) => {
  const [exportingFormat, setExportingFormat] = useState<'xlsx' | 'csv' | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [latestMetadata, setLatestMetadata] = useState<ExportMetadata | null>(null);

  useEffect(() => {
    const unsub = subscribeLatestExportMetadata((meta) => {
      setLatestMetadata(meta);
    });
    return () => unsub();
  }, []);

  const handleExport = async (format: 'xlsx' | 'csv') => {
    if (!profile) {
      setErrorMessage('Unable to generate export: User profile not authenticated.');
      return;
    }

    setExportingFormat(format);
    setSuccessMessage(null);
    setErrorMessage(null);

    try {
      const res = await generateParticipantExport(profile, format);
      setSuccessMessage(
        `✓ Export generated successfully: ${res.fileName} (${res.recordCount} participant records exported)`
      );
    } catch (err: any) {
      console.error('Participant export error:', err);
      setErrorMessage(
        err.message?.includes('ACCESS_DENIED')
          ? 'Access Denied: You are not authorized to export complete participant data.'
          : 'Unable to generate export. Please try again or contact system administration.'
      );
    } finally {
      setExportingFormat(null);
    }
  };

  return (
    <div className="bg-slate-900/80 border border-slate-800 backdrop-blur-md rounded-2xl p-6 shadow-xl relative overflow-hidden my-6">
      {/* Visual Accent Glow */}
      <div className="absolute -top-24 -right-24 w-60 h-60 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-24 -left-24 w-60 h-60 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-2 max-w-2xl">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-gradient-to-br from-amber-500/20 to-orange-500/20 border border-amber-500/30 rounded-xl text-amber-400">
              <Download className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white tracking-wide flex items-center gap-2">
                {title}
                <Badge variant="amber" className="text-xs uppercase tracking-wider font-semibold">
                  Authorized Operations
                </Badge>
              </h3>
              <p className="text-slate-400 text-sm mt-0.5">{subtitle}</p>
            </div>
          </div>

          {/* Real-Time Latest Export Status */}
          {latestMetadata && (
            <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-950/60 border border-slate-800/80 px-3 py-1.5 rounded-lg w-fit mt-3">
              <Clock className="w-3.5 h-3.5 text-amber-400 shrink-0" />
              <span>
                Latest Export:{' '}
                <strong className="text-white">{latestMetadata.fileName}</strong> ({latestMetadata.recordCount} records) generated by{' '}
                <span className="text-amber-300 font-medium">{latestMetadata.generatedBy}</span> ({latestMetadata.generatedByRole})
              </span>
            </div>
          )}
        </div>

        {/* Action Controls */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 shrink-0">
          <Button
            variant="secondary"
            onClick={() => handleExport('xlsx')}
            disabled={exportingFormat !== null}
            className="bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/40 hover:border-emerald-400 px-5 py-2.5 rounded-xl font-semibold flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-900/20"
          >
            {exportingFormat === 'xlsx' ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin text-emerald-400" />
                <span>Generating Excel...</span>
              </>
            ) : (
              <>
                <FileSpreadsheet className="w-4 h-4 text-emerald-400" />
                <span>Download Excel</span>
              </>
            )}
          </Button>

          <Button
            variant="secondary"
            onClick={() => handleExport('csv')}
            disabled={exportingFormat !== null}
            className="bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 border border-blue-500/40 hover:border-blue-400 px-5 py-2.5 rounded-xl font-semibold flex items-center justify-center gap-2 transition-all shadow-lg shadow-blue-900/20"
          >
            {exportingFormat === 'csv' ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin text-blue-400" />
                <span>Generating CSV...</span>
              </>
            ) : (
              <>
                <FileText className="w-4 h-4 text-blue-400" />
                <span>Download CSV</span>
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Notifications */}
      {successMessage && (
        <div className="mt-4 p-3.5 bg-emerald-950/80 border border-emerald-500/40 rounded-xl text-emerald-300 text-sm flex items-center gap-2.5 animate-fadeIn">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{successMessage}</span>
        </div>
      )}

      {errorMessage && (
        <div className="mt-4 p-3.5 bg-rose-950/80 border border-rose-500/40 rounded-xl text-rose-300 text-sm flex items-center gap-2.5 animate-fadeIn">
          <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
          <span>{errorMessage}</span>
        </div>
      )}
    </div>
  );
};
